---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool-deployment
  namespace: team5
  labels:
    app: tool
spec:
  replicas: 2 # 副本数量。 创建ReplicaSet管理
  selector:   # 选择器
    matchLabels:  # 选择 匹配标签 app=appx 的 Pods
      app: tool
  template:  # Pod模版
    metadata:
      labels:  # Pod 标签
        app: tool
    spec:
      containers:  # Pod包含的容器
        - name: tool-container
          image: yinli2020-docker.pkg.coding.net/beijing-backend/team5/tool_module3:latest
          env: # 环境变量
            - name: tool_VERSION
              value: 1.0.0
          ports:  # 容器暴露的端口号
            - containerPort: 8088
      imagePullSecrets:
        - name: yinli-coding-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: tool-service
  namespace: team5
spec:
  selector:  # 匹配标签 app=appx 的 Pods
    app: tool
  ports:
    - protocol: TCP  # 服务协议
      port: 8088   # 服务端口号
      targetPort: 8088 # 目标Pod的端口号
      name: http

